#!/usr/bin/env python
#
# cloud - an easy to use tool for spawning disposable VM on an Openstack
#         cloud
#
# Francois Deppierraz <francois.deppierraz@nimag.net>
#
# License GPLv2+ applies

import os
import sys
import re
import time
import subprocess
import pickle
import tempfile
import logging
import argparse
import ipaddr
from os import environ as env
from getpass import getpass
import random
import os_client_config
import novaclient
from keystoneclient.auth.identity import v2
from keystoneclient import session
from keystoneclient.v2_0 import client as keystone_client
from novaclient import client as nova_client
from neutronclient.v2_0 import client as neutron_client
from cinderclient.v1 import client as cinder_client
import keystoneauth1

IMAGE     = 'ubuntu|xenial'
FLAVOR    = 'm1.small'
KEY_NAME  = os.environ['USER']

SSH_SLEEP = 1
INSTANCE_SLEEP = 5
VOLUME_SLEEP = 1

KNOWN_HOSTS = tempfile.NamedTemporaryFile()
CLEANUPS = []

# Copied from http://bazaar.launchpad.net/~maas-committers/maas/trunk/view/head:/src/maasserver/migrations/0103_candidate_names.py
ADJECTIVES = """\
abandoned able absolute academic acceptable acclaimed accomplished
accurate aching acidic acrobatic active actual adept admirable admired
adolescent adorable adored advanced adventurous affectionate afraid aged
aggravating aggressive agile agitated agonizing agreeable ajar alarmed
alarming alert alienated alive all altruistic amazing ambitious ample
amused amusing anchored ancient angelic angry anguished animated annual
another antique anxious any apprehensive appropriate apt arctic arid
aromatic artistic ashamed assured astonishing athletic attached
attentive attractive austere authentic authorized automatic avaricious
average aware awesome awful awkward babyish back bad baggy bare barren
basic beautiful belated beloved beneficial best better bewitched big
biodegradable bitesize bitter black bland blank blaring bleak blind
blissful blond blue blushing bogus boiling bold bony boring bossy both
bouncy bountiful bowed brave breakable brief bright brilliant brisk
broken bronze brown bruised bubbly bulky bumpy buoyant burdensome burly
bustling busy buttery buzzing calculating calm candid canine capital
carefree careful careless caring cautious cavernous celebrated charming
cheap cheerful cheery chief chilly chubby circular classic clean clear
clever close closed cloudy clueless clumsy cluttered coarse cold
colorful colorless colossal comfortable common compassionate competent
complete complex complicated composed concerned concrete confused
conscious considerate constant content conventional cooked cool
cooperative coordinated corny corrupt costly courageous courteous crafty
crazy creamy creative creepy criminal crisp critical crooked crowded
cruel crushing cuddly cultivated cultured cumbersome curly curvy cute
cylindrical damaged damp dangerous dapper daring dark darling dazzling
dead deadly deafening dear dearest decent decimal decisive deep
defenseless defensive defiant deficient definite definitive delayed
delectable delicious delightful delirious demanding dense dental
dependable dependent descriptive deserted detailed determined devoted
different difficult digital diligent dim dimpled dimwitted direct dirty
disastrous discrete disfigured disguised disgusting dishonest disloyal
dismal distant distinct distorted dizzy dopey doting double downright
drab drafty dramatic dreary droopy dry dual dull dutiful each eager
early earnest easy easygoing ecstatic edible educated elaborate elastic
elated elderly electric elegant elementary elliptical embarrassed
embellished eminent emotional empty enchanted enchanting energetic
enlightened enormous enraged entire envious equal equatorial essential
esteemed ethical euphoric even evergreen everlasting every evil exalted
excellent excitable excited exciting exemplary exhausted exotic
expensive experienced expert extraneous extroverted fabulous failing
faint fair faithful fake false familiar famous fancy fantastic far
faraway fast fat fatal fatherly favorable favorite fearful fearless
feisty feline female feminine few fickle filthy fine finished firm first
firsthand fitting fixed flaky flamboyant flashy flat flawed flawless
flickering flimsy flippant flowery fluffy fluid flustered focused fond
foolhardy foolish forceful forked formal forsaken forthright fortunate
fragrant frail frank frayed free french frequent fresh friendly
frightened frightening frigid frilly frivolous frizzy front frosty
frozen frugal fruitful full fumbling functional funny fussy fuzzy
gargantuan gaseous general generous gentle genuine giant giddy gifted
gigantic giving glamorous glaring glass gleaming gleeful glistening
glittering gloomy glorious glossy glum golden good gorgeous graceful
gracious grand grandiose granular grateful grave gray great greedy green
gregarious grim grimy gripping grizzled gross grotesque grouchy grounded
growing growling grown grubby gruesome grumpy guilty gullible gummy
hairy half handmade handsome handy happy hard harmful harmless
harmonious harsh hasty hateful haunting healthy heartfelt hearty
heavenly heavy hefty helpful helpless hidden hideous high hilarious
hoarse hollow homely honest honorable honored hopeful horrible
hospitable hot huge humble humiliating humming humongous hungry hurtful
husky icky icy ideal idealistic identical idiotic idle idolized ignorant
ill illegal illiterate illustrious imaginary imaginative immaculate
immaterial immediate immense impartial impassioned impeccable imperfect
imperturbable impish impolite important impossible impractical
impressionable impressive improbable impure inborn incomparable
incompatible incomplete inconsequential incredible indelible indolent
inexperienced infamous infantile infatuated inferior infinite informal
innocent insecure insidious insignificant insistent instructive
insubstantial intelligent intent intentional interesting internal
international intrepid ironclad irresponsible irritating itchy jaded
jagged jaunty jealous jittery joint jolly jovial joyful joyous jubilant
judicious juicy jumbo jumpy junior juvenile kaleidoscopic keen key kind
kindhearted kindly klutzy knobby knotty knowing knowledgeable known
kooky kosher lame lanky large last lasting late lavish lawful lazy
leading leafy lean left legal legitimate light lighthearted likable
likely limited limp limping linear lined liquid little live lively livid
loathsome lone lonely long loose lopsided lost loud lovable lovely
loving low loyal lucky lumbering luminous lumpy lustrous luxurious mad
magnificent majestic major male mammoth married marvelous masculine
massive mature meager mealy mean measly meaty medical mediocre medium
meek mellow melodic memorable menacing merry messy metallic mild milky
mindless miniature minor minty miserable miserly misguided misty mixed
modern modest moist monstrous monthly monumental moral mortified
motherly motionless mountainous muddy muffled multicolored mundane murky
mushy musty muted mysterious naive narrow nasty natural naughty nautical
near neat necessary needy negative neglected negligible neighboring
nervous new next nice nifty nimble nippy nocturnal noisy nonstop normal
notable noted noteworthy novel noxious numb nutritious nutty obedient
obese oblong obvious occasional odd oddball offbeat offensive official
oily old overlooked only open optimal optimistic opulent orange orderly
ordinary organic original ornate ornery other our outgoing outlandish
outlying outrageous outstanding oval overcooked overdue overjoyed
palatable pale paltry parallel parched partial passionate past pastel
peaceful peppery perfect perfumed periodic perky personal pertinent
pesky pessimistic petty phony physical piercing pink pitiful plain
plaintive plastic playful pleasant pleased pleasing plump plush pointed
pointless poised polished polite political poor popular portly posh
positive possible potable powerful powerless practical precious present
prestigious pretty previous pricey prickly primary prime pristine
private prize probable productive profitable profuse proper proud
prudent punctual pungent puny pure purple pushy putrid puzzled puzzling
quaint qualified quarrelsome quarterly queasy querulous questionable
quick quiet quintessential quirky quixotic quizzical radiant ragged
rapid rare rash raw ready real realistic reasonable recent reckless
rectangular red reflecting regal regular reliable relieved remarkable
remorseful remote repentant repulsive required respectful responsible
revolving rewarding rich right rigid ringed ripe roasted robust rosy
rotating rotten rough round rowdy royal rubbery ruddy rude rundown runny
rural rusty sad safe salty same sandy sane sarcastic sardonic satisfied
scaly scarce scared scary scented scholarly scientific scornful scratchy
scrawny second secondary secret selfish sentimental separate serene
serious serpentine several severe shabby shadowy shady shallow shameful
shameless sharp shimmering shiny shocked shocking shoddy short showy
shrill shy sick silent silky silly silver similar simple simplistic
sinful single sizzling skeletal skinny sleepy slight slim slimy slippery
slow slushy small smart smoggy smooth smug snappy snarling sneaky
sniveling snoopy sociable soft soggy solid somber some sophisticated
sore sorrowful soulful soupy sour spanish sparkling sparse specific
spectacular speedy spherical spicy spiffy spirited spiteful splendid
spotless spotted spry square squeaky squiggly stable staid stained stale
standard starchy stark starry steel steep sticky stiff stimulating
stingy stormy straight strange strict strident striking striped strong
studious stunning stupendous stupid sturdy stylish subdued submissive
substantial subtle suburban sudden sugary sunny super superb superficial
superior supportive surprised suspicious svelte sweaty sweet sweltering
swift sympathetic talkative tall tame tan tangible tart tasty tattered
taut tedious teeming tempting tender tense tepid terrible terrific testy
thankful that these thick thin third thirsty this thorny thorough those
thoughtful threadbare thrifty thunderous tidy tight timely tinted tiny
tired torn total tough tragic trained traumatic treasured tremendous
triangular tricky trifling trim trivial troubled true trusting
trustworthy trusty truthful tubby turbulent twin ugly ultimate
unacceptable unaware uncomfortable uncommon unconscious understated
unequaled uneven unfinished unfit unfolded unfortunate unhappy unhealthy
uniform unimportant unique united unkempt unknown unlawful unlined
unlucky unnatural unpleasant unrealistic unripe unruly unselfish
unsightly unsteady unsung untidy untimely untried untrue unused unusual
unwelcome unwieldy unwilling unwitting unwritten upbeat upright upset
urban usable used useful useless utilized utter vacant vague vain valid
valuable vapid variable vast velvety venerated vengeful verifiable
vibrant vicious victorious vigilant vigorous villainous violent violet
virtual virtuous visible vital vivacious vivid voluminous wan warlike
warm warmhearted warped wary wasteful watchful waterlogged watery wavy
weak wealthy weary webbed wee weekly weepy weighty weird welcome wet
which whimsical whirlwind whispered white whole whopping wicked wide
wiggly wild willing wilted winding windy winged wiry wise witty wobbly
woeful wonderful wooden woozy wordy worldly worn worried worrisome worse
worst worthless worthwhile worthy wrathful wretched writhing wrong wry
yawning yearly yellow yellowish young youthful yummy zany zealous zesty
zigzag"""

NOUNS = """\
account achiever acoustics act action activity actor addition adjustment
advertisement advice aftermath afternoon afterthought agreement air
airplane airport alarm alley amount amusement anger angle animal answer
ant ants apparatus apparel apple apples appliance approval arch argument
arithmetic arm army art attack attempt attention attraction aunt
authority babies baby back badge bag bait balance ball balloon balls
banana band base baseball basin basket basketball bat bath battle bead
beam bean bear bears beast bed bedroom beds bee beef beetle beggar
beginner behavior belief believe bell bells berry bike bikes bird birds
birth birthday bit bite blade blood blow board boat boats body bomb bone
book books boot border bottle boundary box boy boys brain brake branch
brass bread breakfast breath brick bridge brother brothers brush bubble
bucket building bulb bun burn burst bushes business butter button
cabbage cable cactus cake cakes calculator calendar camera camp can
cannon canvas cap caption car card care carpenter carriage cars cart
cast cat cats cattle cause cave celery cellar cemetery cent chain chair
chairs chalk chance change channel cheese cherries cherry chess chicken
chickens children chin church circle clam class clock clocks cloth cloud
clouds clover club coach coal coast coat cobweb coil collar color comb
comfort committee company comparison competition condition connection
control cook copper copy cord cork corn cough country cover cow cows
crack cracker crate crayon cream creator creature credit crib crime
crook crow crowd crown crush cry cub cup current curtain curve cushion
dad daughter day death debt decision deer degree design desire desk
destruction detail development digestion dime dinner dinosaurs direction
dirt discovery discussion disease disgust distance distribution division
dock doctor dog dogs doll dolls donkey door downtown drain drawer dress
drink driving drop drug drum duck ducks dust ear earth earthquake edge
education effect egg eggnog eggs elbow end engine error event example
exchange existence expansion experience expert eye eyes face fact
fairies fall family fan fang farm farmer father faucet fear feast
feather feeling feet fiction field fifth fight finger fire fireman fish
flag flame flavor flesh flight flock floor flower flowers fly fog fold
food foot force fork form fowl frame friction friend friends frog frogs
front fruit fuel furniture game garden gate geese ghost giants giraffe
girl girls glass glove glue goat gold goldfish goose government governor
grade grain grandfather grandmother grape grass grip ground group growth
guide guitar gun hair haircut hall hammer hand hands harbor harmony hat
hate head health hearing heart heat help hen hill history hobbies hole
holiday home honey hook hope horn horse horses hose hospital hot hour
house houses humor hydrant ice icicle idea impulse income increase
industry ink insect instrument insurance interest invention iron island
jail jam jar jeans jelly jellyfish jewel join joke journey judge juice
jump kettle key kick kiss kite kitten kittens kitty knee knife knot
knowledge laborer lace ladybug lake lamp land language laugh lawyer lead
leaf learning leather leg legs letter letters lettuce level library lift
light limit line linen lip liquid list lizards loaf lock locket look
loss love low lumber lunch lunchroom machine magic maid mailbox man
manager map marble mark market mask mass match meal measure meat meeting
memory men metal mice middle milk mind mine minister mint minute mist
mitten mom money monkey month moon morning mother motion mountain mouth
move muscle music nail name nation neck need needle nerve nest net news
night noise north nose note notebook number nut oatmeal observation
ocean offer office oil operation opinion orange oranges order
organization ornament oven owl owner page pail pain paint pan pancake
paper parcel parent park part partner party passenger paste patch
payment peace pear pen pencil person pest pet pets pickle picture pie
pies pig pigs pin pipe pizzas place plane planes plant plantation plants
plastic plate play playground pleasure plot plough pocket point poison
police polish pollution popcorn porter position pot potato powder power
price print prison process produce profit property prose protest pull
pump punishment purpose push quarter quartz queen question quicksand
quiet quill quilt quince quiver rabbit rabbits rail railway rain
rainstorm rake range rat rate ray reaction reading reason receipt recess
record regret relation religion representative request respect rest
reward rhythm rice riddle rifle ring rings river road robin rock rod
roll roof room root rose route rub rule run sack sail salt sand scale
scarecrow scarf scene scent school science scissors screw sea seashore
seat secretary seed selection self sense servant shade shake shame shape
sheep sheet shelf ship shirt shock shoe shoes shop show side sidewalk
sign silk silver sink sister sisters size skate skin skirt sky slave
sleep sleet slip slope smash smell smile smoke snail snails snake snakes
sneeze snow soap society sock soda sofa son song songs sort sound soup
space spade spark spiders sponge spoon spot spring spy square squirrel
stage stamp star start statement station steam steel stem step stew
stick sticks stitch stocking stomach stone stop store story stove
stranger straw stream street stretch string structure substance sugar
suggestion suit summer sun support surprise sweater swim swing system
table tail talk tank taste tax teaching team teeth temper tendency tent
territory test texture theory thing things thought thread thrill throat
throne thumb thunder ticket tiger time tin title toad toe toes tomatoes
tongue tooth toothbrush toothpaste top touch town toy toys trade trail
train trains tramp transport tray treatment tree trees trick trip
trouble trousers truck trucks tub turkey turn twig twist umbrella uncle
underwear unit use vacation value van vase vegetable veil vein verse
vessel vest view visitor voice volcano volleyball voyage walk wall war
wash waste watch water wave waves wax way wealth weather week weight
wheel whip whistle wilderness wind window wine wing winter wire wish
woman women wood wool word work worm wound wren wrench wrist writer
writing yak yam yard yarn year yoke zebra zephyr zinc zipper zoo"""

def setup_environment():
  if not 'OS_AUTH_URL' in os.environ:
    source = '. ~/.openrc'
    dump = '/usr/bin/python -c "import os,pickle;print pickle.dumps(os.environ)"'
    penv = os.popen('%s && %s' %(source,dump))
    env = pickle.loads(penv.read())
    os.environ = env
  
  if not 'OS_PASSWORD' in os.environ:
    password = getpass("OS Password: ")
    os.environ['OS_PASSWORD'] = password

def ssh(args):
  logging.debug("ssh " + repr(args))
  return subprocess.call(['ssh', '-q', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=%s' % KNOWN_HOSTS.name] + args)

def scp(args):
  logging.debug("scp" + repr(args))
  return subprocess.call(['scp', '-q', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=%s' % KNOWN_HOSTS.name] + args)

def get_floating_ip_pool(nova):
  if args.floating_ip_pool:
    for p in nova.floating_ip_pools.list():
      logging.debug('Nova floating ip pool: %s', p)
      if p.name == args.floating_ip_pool:
        return p

    # No specified pool found
    raise Exception('Floating IP pool %s not found', args.floating_ip_pool)
  else:
    # No specific pool request, let's just return the first one
    return nova.floating_ip_pools.list()[0]

def get_global_ip(nova, instance):
  logging.debug("Instance addresses: %s", instance.addresses)
  for net in instance.addresses:
    for address in instance.addresses[net]:
      ip = ipaddr.IPAddress(address['addr'])

      if not ip.is_private:
        if args.prefer_ipv4 and ip.version != 4:
          logging.debug("%s address is not IPv4", ip)
          continue

        if args.prefer_ipv6 and ip.version != 6:
          logging.debug("%s address is not IPv6", ip)
          continue

        logging.debug("Found global IP address: %s", ip)
        return ip

  if args.no_floating_ip:
    return ip

  pool = get_floating_ip_pool(nova)

  ip = nova.floating_ips.create(pool.name)
  CLEANUPS.append(ip)
  logging.debug("Floating IP %s" % ip.ip)
  instance.add_floating_ip(ip)
  return ip.ip

def get_flavor(nova, name):
  for flavor in nova.flavors.list():
    if name in flavor.name:
      return flavor
  raise Exception('No flavor %s found' % name)

def get_nic(neutron, keystone, net):
  try:
    neutron.list_networks()
  except Exception, e:
    logging.warn("No neutron support found, let's hope nova will handle the network")
    logging.exception(e)
    return None

  if net:
    nets = neutron.list_networks(name=net)['networks']

    logging.debug("Available networks: %s", nets)

    try:
      nic = {'net-id': nets[0]['id']}
    except novaclient.exceptions.NotFound:
      raise Exception("Network %s not found" % net)
  else:
    # From horizon/openstack_dashboard/api/neutron.py network_list_for_tenant()
    nets = neutron.list_networks(tenant_id=keystone.tenant_id, shared=False)['networks']
    nets += neutron.list_networks(shared=True)['networks']

    assert(len(nets) > 0)
    if len(nets) == 1:
      net = nets[0]['id']
      logging.debug("Connecting instance to the only available network %s", net)
      nic = {'net-id': net}
    else:
      raise Exception("Multiple networks found (%s), please specify which one the instance should use with --net" % [net['name'] for net in nets])

  return nic

def find_image(nova, args):
  for image in nova.images.list():
    if image.name and re.match(args.image, image.name, re.IGNORECASE):
      return image.id

  raise Exception("Image %s not found!" % args.image)

def get_bdm(nova, args):
  image_id = find_image(nova, args)

  if args.volume:

    cinder = cinder_client.Client(
      os.environ['OS_USERNAME'],
      os.environ['OS_PASSWORD'],
      os.environ['OS_TENANT_NAME'],
      os.environ['OS_AUTH_URL']
    )

    logging.debug("Create a new volume of type %s based on image %s of size %d GB" % (args.volume_type, image_id, args.volume_size))
    volume = cinder.volumes.create(size=args.volume_size, volume_type=args.volume_type, imageRef=image_id)
    CLEANUPS.append(volume)

    logging.debug("Volume %s created" % volume.id)

    # Wait for volume creation
    while True:
      volume.get()

      if volume.status == 'available':
        break
      if volume.status == 'error':
        raise Exception('Volume creation failed')
      else:
        logging.debug("Volume status: %s" % (volume.status))
        time.sleep(VOLUME_SLEEP)

    logging.debug("Boot from volume %s", volume)
    bdm = [{
      'uuid': volume.id,
      'source_type': 'volume',
      'destination_type': 'volume',
      'delete_on_termination': True,
      'boot_index': 0
    }]
    image = None
  else:
    bdm = None
    image = image_id

  return bdm, image

def main(args, cloud_config):
  logging.debug("Connecting to Openstack cloud")
  
  try:
    cloud = cloud_config.get_one_cloud(argparse=args)

    nova = cloud.get_legacy_client('compute')
    neutron = cloud.get_legacy_client('network')

    try:
      keystone = cloud.get_legacy_client('identity', version=3)
    except keystoneauth1.exceptions.discovery.VersionNotAvailable:
      keystone = cloud.get_legacy_client('identity', version=2)

    flavor = get_flavor(nova, args.flavor)
    nics = []
    if args.net:
      for net in args.net:
        nics.append(get_nic(neutron, keystone, net))
    logging.debug('Nics: %s' % (nics))
    bdm, image = get_bdm(nova, args)

    instance = nova.servers.create(
      name=args.name,
      image=image,
      flavor=flavor.id,
      key_name=args.key_name,
      nics=nics,
      block_device_mapping_v2 = bdm,
      availability_zone = args.availability_zone
    )
    CLEANUPS.insert(0, instance)

    logging.debug("Instance %s" % instance.id)
  
    while True:
      instance = nova.servers.get(instance.id)
      logging.debug("Instance status: %s" % instance.status)
      if instance.status == 'ERROR':
        logging.error("Instance ID: %s" % (instance.id))
        raise Exception('Instance creation failure')
      if instance.addresses != {}:
        logging.debug("IP addresses present")
        break
      else:
        time.sleep(INSTANCE_SLEEP)

    ssh_ip = get_global_ip(nova, instance)
    logging.debug("Globally reachable IP: %s", ssh_ip)

    try:
      instance.add_security_group(args.secgroup)

    # default security group not found, create it
    except novaclient.exceptions.NotFound:
      if args.secgroup == 'all':
        secgroup = nova.security_groups.create('all', 'The world famous any any rule')
        nova.security_group_rules.create(secgroup.id, 'icmp', '-1', '-1', '0.0.0.0/0') 
        nova.security_group_rules.create(secgroup.id, 'udp', '1', '65535', '0.0.0.0/0') 
        nova.security_group_rules.create(secgroup.id, 'tcp', '1', '65535', '0.0.0.0/0') 
        instance.add_security_group(secgroup.id)

    # API not supported by rackspace cloud
    except novaclient.exceptions.BadRequest:
      pass

    while True:
      res = ssh(['%s@%s' % (args.user, ssh_ip), 'echo'])
      if res == 0:
        break
      else:
        time.sleep(SSH_SLEEP)

    if args.script:
      logging.debug("Executing user supplied script: %s", args.script)
      scp([os.path.abspath(args.script), '%s@%s:/tmp/script' % (args.user, ssh_ip)])
      if args.root:
        ssh(['-t', '%s@%s' % (args.user, ssh_ip), 'chmod +x /tmp/script && sudo /tmp/script'])
      else:
        ssh(['-t', '%s@%s' % (args.user, ssh_ip), 'chmod +x /tmp/script && /tmp/script'])
    elif args.command:
      logging.debug("Executing user supplied command: %s", args.command)
      ssh(['-t', '%s@%s' % (args.user, ssh_ip), args.command])
    else:
      logging.debug("Executing interactive shell")
      ssh(['-t', '%s@%s' % (args.user, ssh_ip)])

  finally:
    if not args.permanent:
      logging.debug("Cleanup...")

      for cleanup in CLEANUPS:
        try:
          cleanup.delete()
          logging.debug("%s deleted", cleanup)
        except Exception, e:
          # Known openstack bug:
          # https://bugs.launchpad.net/tempest/+bug/1586931
          if 'neutronclient.common.exceptions.PortNotFoundClient' in e.message:
            break

          logging.warn("Deletion of resource %s failed", cleanup)
          logging.exception(e)

def get_hostname():
  adjective = random.choice(ADJECTIVES.replace('\n', ' ').strip().split(' '))
  noun = random.choice(NOUNS.replace('\n', ' ').strip().split(' '))

  return 'cloud-%s-%s' % (adjective, noun)

def usage():
  print("Usage: %s [script]" % sys.argv[0])

if __name__ == '__main__':
  global DEBUG

  parser = argparse.ArgumentParser(description='Easy to use tool for spawning disposable VM on an Openstack')
  parser.add_argument('--debug', '-d', action='store_true')
  parser.add_argument('--image', '-i', default=IMAGE)
  parser.add_argument('--flavor', '-f', default=FLAVOR)
  parser.add_argument('--name', '-n', default=get_hostname())
  parser.add_argument('--net', action='append')
  parser.add_argument('--no-floating-ip', action='store_true')
  parser.add_argument('--floating-ip-pool')
  parser.add_argument('--permanent', '-p', action='store_true')
  parser.add_argument('--root', '-r', action='store_true')
  parser.add_argument('--command', '-c')
  parser.add_argument('--key-name', '-k', default=KEY_NAME)
  parser.add_argument('--volume', '-v', action='store_true')
  parser.add_argument('--volume-size', '-s', type=int, default=10)
  parser.add_argument('--volume-type', '-t')
  parser.add_argument('--user', '-u', default='ubuntu')
  parser.add_argument('--secgroup', default='all')
  parser.add_argument('--availability_zone', '-az')

  group = parser.add_mutually_exclusive_group()
  group.add_argument('--prefer-ipv4', '-4', action='store_true')
  group.add_argument('--prefer-ipv6', '-6', action='store_true')

  parser.add_argument('script', nargs='?', default=False, help='Script that will automatically be run inside the VM')

  cloud_config = os_client_config.OpenStackConfig()
  cloud_config.register_argparse_arguments(parser, sys.argv)
  args = parser.parse_args()

  if args.debug:
    logger = logging.getLogger()
    logger.setLevel(logging.DEBUG)

    logging.getLogger('iso8601.iso8601').setLevel(logging.WARN)

  try:
    setup_environment()
    main(args, cloud_config)
  finally:
    KNOWN_HOSTS.close()
